/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用戶註冊 */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupRequest: {
            /** @example 張三 */
            name: string;
            /**
             * Format: email
             * @example zhang@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
            /** @example password123 */
            passwordConfirm: string;
        };
        SignupResponse: {
            /** @example 註冊成功，請檢查您的信箱 */
            message?: string;
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["User"];
        };
        User: {
            _id?: string;
            name?: string;
            email?: string;
            /** @enum {string} */
            role?: "user" | "admin";
            emailVerified?: boolean;
        };
        ErrorResponse: {
            message?: string;
            /** @example false */
            success?: boolean;
            errors?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 註冊成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description 驗證失敗 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
